In [75]:
my_list = [1,2,3]

In [76]:
my_list

[1, 2, 3]

In [77]:
import numpy as np

In [78]:
np.array(my_list)

array([1, 2, 3])

In [79]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [80]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**RANGE**

**Use np.arange(start, stop, step)**
This will return evenly spaced value within the given intervals

In [81]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [83]:
# TO generate arrays of zeros
np.zeros(3)
#This gives you an answer in 1D (One dimension)

array([0., 0., 0.])

In [84]:
np.zeros((5,5))
#first number represent number of rows and the second represent number of columns
#This gives a tuples of the dimension you want

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [86]:
np.ones(4)

array([1., 1., 1., 1.])

In [87]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:
#LINSPACE: This returns evenly spaced number for a specified intervals
#Dont confuse lindspace for range
#Linspace takes a third argument as the number of points you want WHILE Arrays takes third argument as the step you want

# **np.linspace(start, stop, num...)**

#This returns 10 evenly spaced numbers from 0 to 5

In [89]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [90]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

Dont think the above is two dimensional because of how it appears to be in rows and columns, it is one dimensional.

One Dimensional has its array output as one square bracket ([])
Two Dimensional has it's as two square brackets ([[]])

**CREATING AN IDENTITY MATRIX USING NUMPY**

An identity matrix is a type of matrix useful when dealing with linear algebra problems is a two dimensional square matrix (has same number of rows and columns) and you have a diagonal of ones and every other thing is zero

In [91]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [150]:
# Random Numbers
np.random.rand(5)
# rand gives an array of the given space you passed in and give it an array and populate with random samples of a uniform 
#distribution from zero to one (0 - 1)

array([0.51807419, 0.24484898, 0.85527272, 0.8268481 , 0.7091383 ])

In [149]:
np.random.rand(5, 5)

array([[0.78293089, 0.72043887, 0.69090202, 0.88098848, 0.7841768 ],
       [0.93941376, 0.38519929, 0.70001636, 0.08223947, 0.84844385],
       [0.90674243, 0.73575011, 0.93367234, 0.90899394, 0.81292281],
       [0.18091768, 0.14799709, 0.22488919, 0.08755352, 0.02426302],
       [0.6654779 , 0.99246806, 0.84591061, 0.8424392 , 0.55741677]])

In [151]:
np.random.randn(2)
#randn gives numbers from standard normal distribution of zeros and not from uniform distribution from zero to one

array([-0.74719642,  2.33047941])

In [152]:
np.random.randn(4,4)

array([[-0.35492718, -1.09249032,  0.52459983,  0.22387444],
       [-0.18476395,  1.03943227,  0.72724172, -0.46700864],
       [ 1.52205973,  0.7203907 , -1.24233389,  1.32697625],
       [ 0.15406815, -0.17092612,  0.87963538, -0.29453906]])

In [154]:
np.random.randint(1, 100, 10)

array([30, 75, 63, 12, 47, 76, 41, 38, 90, 36])

In [155]:
np.random.randint(100)

97

In [157]:
arr =np.arange(25)

In [158]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [160]:
ranarr = np.random.randint(0, 50, 10)

In [161]:
ranarr

array([15, 46,  3, 44, 13,  1, 16, 35, 46,  6])

In [164]:
#RESHAPE METHOD - you must fill up the space completely (5 * 5 = 25 elements)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [166]:
ranarr.max()

46

In [168]:
ranarr.min()

1

In [169]:
ranarr.argmax() # This gives the index location of where the maximum value is located

1

In [170]:
ranarr.argmin()

5

In [171]:
arr.shape

(25,)

In [176]:
arr = arr.reshape(5, 5)

In [177]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [178]:
arr.shape

(5, 5)

In [179]:
arr.dtype

dtype('int32')

In [181]:
# You can use 
from numpy.random import randint

In [182]:
randint(2,10)

3

In [95]:
import numpy as np

In [96]:
arr = np.arange(0,11)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr[8]

8

In [99]:
# Using slice notation

arr[1:5]

array([1, 2, 3, 4])

In [100]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [101]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [102]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
arr[0:5] = 100

In [104]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [105]:
arr = np.arange(0,11)

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
slice_of_arr = arr[0:6]

In [108]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [109]:
slice_of_arr[:] = 99

In [110]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [111]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [112]:
#8mins

arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [113]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [114]:
arr_2d[0]

array([ 5, 10, 15])

In [115]:
arr_2d[0][0]

5

In [116]:
arr_2d[1][1]

25

In [117]:
arr_2d[2][2]

45

In [118]:
# You can use single bracket notation but you just use a comma
arr_2d[1,2]

30

In [119]:
arr_2d[1,1]

25

In [120]:
# To grab only top right corner i.e. only 10, 15, 25, 30
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [121]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

CONDITIONAL SELECTION

In [122]:
arr = np.arange(1,11)

In [123]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [125]:
bool_arr = arr > 5

In [126]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [127]:
# We can use this to do a conditional selection
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [128]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [129]:
#we'll use the above alot

In [130]:
arr_2d = np.arange(50).reshape(5,10)

In [131]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [132]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

**Numpy Operations**
- Array with Array
- Array with Scalars
- Universal Array Functions

In [133]:
import numpy as np

In [134]:
arr = np.arange(0, 11)

In [135]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [137]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [183]:
# Arrays with scalar operations
# Scalars mean just a single number so numpy attach the number to all values and elements in the array
arr + 100

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124]])

In [140]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [141]:
arr / arr

C:\Users\Hussein\AppData\Local\Temp\ipykernel_4132\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [142]:
# nan is because of the division by zero and numpy still gives you a result but as (none) plus a warning
# 1/arr for the first element which is zero will be 1 / 0 and will give (inf) i.e. infinity

In [143]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [144]:
# **UNIVERSAL ARRAY FUNCTIONS**
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [145]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [146]:
np.max(arr)

10

In [147]:
arr.max ()

10

In [148]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [198]:
# NUMPY EXERCISES

In [184]:
import numpy as np

In [190]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [186]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [194]:
arr = np.arange(1,11)

In [195]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [196]:
arr[:] = 5

In [197]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [200]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [201]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [202]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [204]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [206]:
np.random.rand(1)

array([0.26066419])

In [207]:
np.random.randn(25)

array([ 0.97305871,  1.31600775,  0.52354805, -0.27608734, -0.88572548,
       -0.96515811,  0.21571251, -1.5487127 ,  1.41196987, -0.17421541,
        0.02623277,  0.9722205 , -1.18031293,  0.82054397, -0.25234628,
        0.75152388, -0.06946878, -0.9279171 , -1.00315348, -0.5609336 ,
        0.74121627,  0.17874738, -1.01191853,  1.29482195,  0.17601686])

In [209]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [210]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [211]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [212]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [213]:
mat[3,4]

20

In [215]:
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [216]:
mat[4,0:]

array([21, 22, 23, 24, 25])

In [218]:
mat[3:5,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [219]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [220]:
#The sum of all values in mat
np.sum(mat)

325

In [221]:
# or
mat.sum()

325

In [222]:
# Standard deviation
np.std(mat)
#or
mat.std()

7.211102550927978

In [223]:
mat.sum(axis=0) # This will get the sum of all columns in mat

array([55, 60, 65, 70, 75])